language: php

dist: bionic

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

install:
  - travis_retry composer update ${COMPOSER_FLAGS}

script:
  - vendor/bin/phpunit
